{% set version = "1.4.2" %}

package:
  name: adwaita-qt6
  version: {{ version }}

source:
  url: https://github.com/FedoraQt/adwaita-qt/archive/{{ version }}.tar.gz
  sha256: cd5fd71c46271d70c08ad44562e57c34e787d6a8650071db115910999a335ba8
  patches:
    # I think this patch is required because
    # https://github.com/conda-forge/qt-main-feedstock/issues/121
    - do_not_add_qt_include_directories.patch

build:
  skip: true  # [not linux]
  number: 1
  run_exports:
    # Just a guess...
    - {{ pin_subpackage('adwaita-qt6', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - qt6-main                           # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
  host:
    - qt6-main
    - libxcb

test:
  commands:
    - test -f ${PREFIX}/lib/qt6/plugins/styles/adwaita.so
    - test -f ${PREFIX}/lib/libadwaitaqt6.so

about:
  home: https://github.com/FedoraQt/adwaita-qt
  summary: 'A native style to bend Qt5/Qt6 applications to look like they belong into GNOME Shell.'
  license: LGPL-2.1-only
  license_family: LGPL
  license_file:
    - COPYING
    - LICENSE.LGPL2
    - LICENSE.GPL2

extra:
  recipe-maintainers:
    - hmaarrfk
